### ISSUE TITLE
Unity 5.4.0f2 compatibility 

### ISSUE THREAD

**Issue by ghost** [quakeboy/TryDoTween#1]
Hi,

I'd like to try your 'Try DoTween' demo scene but when I launch in Unity I'm getting an error from this script:
BestFitOutline line 20:
public override void ModifyVertices (List<UIVertex> verts)

and this is the error message:
UnityEngine.UI.Extensions.BestFitOutline.ModifyVertices(System.Collections.Generic.List<UnityEngine.UIVertex>)' is marked as an override but no suitable method found to override.

Thanks,
Michael

**Comment by quakeboy** [comment]
Hi Michael,

The error seems to be coming from the Unity UI extensions library. Can you update the library from
https://bitbucket.org/Unity-Technologies/ui

and try running it again?

**Comment by ghost** [comment]
Hi Rajavanya,

Thanks for the useful help.

Unfortunately I'm working with a developer who is using an older version of
Unity to develop my app so I don't dare update anything right now in Unity.

After we upgrade to the new version of Unity I will return to your software
and try again.

Thanks,
Michael
